services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASSWORD
    volumes:
      - ./database_objects:/database_objects
      - ./structure:/structure
      - "./${BACKUP_DIR}:/${BACKUP_DIR}:rw"
    ports:
      - "3306:3306"
